export const DiseasesData = [
    "Acne",
    "Allergies",
    "Alzheimer's Disease",
    "Anemia",
    "Anorexia Nervosa",
    "Appendicitis",
    "Arthritis",
    "Asthma",
    "Autism Spectrum Disorder",
    "Bipolar Disorder",
    "Blindness",
    "Bronchitis",
    "Cancer",
    "Celiac Disease",
    "Chronic Fatigue Syndrome",
    "Chronic Kidney Disease",
    "Chronic Obstructive Pulmonary Disease (COPD)",
    "Colitis",
    "Congestive Heart Failure",
    "Cystic Fibrosis",
    "Dengue Fever",
    "Depression",
    "Diabetes",
    "Eating Disorders",
    "Eczema",
    "Endometriosis",
    "Epilepsy",
    "Fibromyalgia",
    "Gastritis",
    "Gastroenteritis",
    "Glaucoma",
    "Gout",
    "Graves' Disease",
    "Hepatitis",
    "Huntington's Disease",
    "Hypertension",
    "Hypothyroidism",
    "Inflammatory Bowel Disease",
    "Insomnia",
    "Irritable Bowel Syndrome (IBS)",
    "Jaundice",
    "Leprosy",
    "Leukemia",
    "Lupus",
    "Lyme Disease",
    "Malaria",
    "Melanoma",
    "Migraine",
    "Multiple Sclerosis",
    "Muscular Dystrophy",
    "Narcolepsy",
    "Obesity",
    "Obsessive-Compulsive Disorder (OCD)",
    "Osteoarthritis",
    "Osteoporosis",
    "Pancreatitis",
    "Parkinson's Disease",
    "Pneumonia",
    "Polio",
    "Post-Traumatic Stress Disorder (PTSD)",
    "Psoriasis",
    "Rheumatoid Arthritis",
    "Schizophrenia",
    "Sickle Cell Anemia",
    "Sleep Apnea",
    "Strep Throat",
    "Stroke",
    "Tinnitus",
    "Tuberculosis",
    "Ulcerative Colitis",
    "Uterine Fibroids",
    "Varicose Veins",
    "Vasculitis",
    "Vitamin Deficiencies",
    "West Nile Virus",
    "Yellow Fever",
    "Zika Virus",
    // Additional diseases
    "Chagas Disease",
    "Diphtheria",
    "Elephantiasis",
    "Hemochromatosis",
    "Kawasaki Disease",
    "Marfan Syndrome",
    "Nephrotic Syndrome",
    "Ovarian Cancer",
    "Pulmonary Hypertension",
    "Rabies",
    "Sarcoidosis",
    "Thalassemia",
    "Typhoid Fever",
    "Whooping Cough (Pertussis)",
    "Xeroderma Pigmentosum",
    // ... (add more as needed)
  ];
  